### ISSUE TITLE
Library does not build on Linux

### ISSUE THREAD

**Issue by rodb70** [ETCLabs/RDMnet#25]
**Describe the bug**
Build error when trying to build on Linux, this looks to be because of a missing header file.

RDMnet/src/rdmnet/discovery/avahi/rdmnet_disc_avahi.c:30:37: fatal error: rdmnet/discovery/common.h: No such file or directory
compilation terminated.
src/rdmnet/CMakeFiles/RDMnet.dir/build.make:322: recipe for target 'src/rdmnet/CMakeFiles/RDMnet.dir/discovery/avahi/rdmnet_disc_avahi.c.o' failed
make[2]: *** [src/rdmnet/CMakeFiles/RDMnet.dir/discovery/avahi/rdmnet_disc_avahi.c.o] Error 1
CMakeFiles/Makefile2:717: recipe for target 'src/rdmnet/CMakeFiles/RDMnet.dir/all' failed
make[1]: *** [src/rdmnet/CMakeFiles/RDMnet.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Clone repository
2. Follow instructions to configure and build
3. See compile failure

**Expected behavior**
Sucessful compile

**Additional context**
Just trying to build from Linux command line.
Linux 'uname -a' output:
Linux defiant 4.15.0-72-generic #81~16.04.1-Ubuntu SMP Tue Nov 26 16:34:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by samkearney** [comment]
Hi @rodb70, yes, the Linux port of the library is not completed at this time. We will have this working in the very near future. You can keep an eye on https://jira.etcconnect.com/browse/RDMNET-20 or on the [docs](https://etclabs.github.io/RDMnet/docs/head/) to indicate Linux as a supported platform; since we have a low issue count right now, I'll also go ahead and just leave this one open and close it when we have Linux support.

**Comment by rodb70** [comment]
No problem close as you see fit.

**Comment by samkearney** [comment]
As of the latest tag baseline v0.3.0.10, the library and example applications should be buildable on Linux. Tested on Ubuntu 18.04 and 20.04.
